<h2>Titanic - Model Selection</h2>

<h3>Importing libraries</h3>

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

<h3>Loading the datasets</h3>

In [2]:
df_train = pd.read_csv("./data/train.csv")
df_test = pd.read_csv("./data/test.csv")

In [3]:
X_train = df_train.iloc[:, df_train.columns != "Survived"].values
y_train = df_train.loc[:, "Survived"].values

In [4]:
X_test = df_test.iloc[:, df_test.columns != "Survived"].values
y_test = df_test.loc[:, "Survived"].values

In [5]:
X_train

array([[-0.57191187,  0.67743918,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.49577531, -0.49665643,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-1.02873125, -0.24956999,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.79854628, -0.46507212,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.64804843,  4.59297793,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.49400002, -0.17156922,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [6]:
X_test

array([[ 0.01427249, -0.49982247,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.02695597, -0.4935724 ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.41963874, -0.5135726 ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.95081941, -0.13456885,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.01427249, -0.33257081,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 2.47355069,  0.94544184,  1.        , ...,  0.        ,
         0.        ,  0.        ]])

In [7]:
y_train

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,

In [8]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1], dtype=int64)

<h3>Training the models</h3>

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

models = []
models.append(LogisticRegression())
models.append(KNeighborsClassifier())
models.append(RandomForestClassifier())
models.append(DecisionTreeClassifier())
models.append(SVC())
models.append(XGBClassifier())


for model in models:
    model.fit(X_train, y_train)
    print(type(model), "has been trained!")

<class 'sklearn.linear_model._logistic.LogisticRegression'> has been trained!
<class 'sklearn.neighbors._classification.KNeighborsClassifier'> has been trained!
<class 'sklearn.ensemble._forest.RandomForestClassifier'> has been trained!
<class 'sklearn.tree._classes.DecisionTreeClassifier'> has been trained!
<class 'sklearn.svm._classes.SVC'> has been trained!
<class 'xgboost.sklearn.XGBClassifier'> has been trained!


<h3>Evaluating the models</h3>

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix

for model in models:
    y_pred = model.predict(X_test)

    print("\nModel:", type(model))
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Model: <class 'sklearn.linear_model._logistic.LogisticRegression'>
Accuracy: 0.776536312849162
Confusion Matrix:
 [[96 19]
 [21 43]]

Model: <class 'sklearn.neighbors._classification.KNeighborsClassifier'>
Accuracy: 0.7988826815642458
Confusion Matrix:
 [[100  15]
 [ 21  43]]

Model: <class 'sklearn.ensemble._forest.RandomForestClassifier'>
Accuracy: 0.770949720670391
Confusion Matrix:
 [[92 23]
 [18 46]]

Model: <class 'sklearn.tree._classes.DecisionTreeClassifier'>
Accuracy: 0.7932960893854749
Confusion Matrix:
 [[98 17]
 [20 44]]

Model: <class 'sklearn.svm._classes.SVC'>
Accuracy: 0.8212290502793296
Confusion Matrix:
 [[102  13]
 [ 19  45]]

Model: <class 'xgboost.sklearn.XGBClassifier'>
Accuracy: 0.776536312849162
Confusion Matrix:
 [[93 22]
 [18 46]]


<h3>Conclusion</h3>
Every model performed quiet well. The best algorithm for this problem is the SVC (Support Vector Classifier).